---
version: 2
jobs:
  check-security:
    docker:
      - image: meliuz/docker-security:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout

      - run:
          name: Check security flaws
          command: docker-entrypoint "check-javascript-security"
  build:
    docker:
      - image: meliuz/node:10.15.1
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - run:
          name: Build
          command: npm run build
  publish-npm-package:
    docker:
      - image: meliuz/node:10.15.1
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - run:
          name: Publish npm package
          command: npm publish

workflows:
  version: 2
  meliuz-workflow:
    jobs:
      - check-security:
          context: global
          filters:
            branches:
              only: /.*?/
            tags:
              only: /.*?/
      - build:
          context: global
          requires:
            - check-security
          filters:
            branches:
              only: /.*?/
            tags:
              only: /.*?/
      - publish-npm-package:
          context: global
          requires:
            - build
          filters:
            branches:
              ignore: /.*?/
            tags:
              only: /^[0-9]+(\.[0-9]+){2}$/
